<?php

include("vendor/autoload.php");

$client = \B3none\SteamIDConverter\Client::create();

/**
 * Generated by SteamID64 | 76561198028510846
 */
$steamUserOne = $client->createFromSteamID64('76561198028510846');
print_r([
    'SteamID64' => $steamUserOne->getSteamID64(),
    'SteamID' => $steamUserOne->getSteamID()
]);

/**
 * Generated by SteamID | STEAM_0:0:34122559
 */
$steamUserTwo = $client->createFromSteamID('STEAM_0:0:34122559');
print_r([
    'SteamID64' => $steamUserTwo->getSteamID64(),
    'SteamID' => $steamUserTwo->getSteamID()
]);
